[tools]
node = "22"

[env]
# You can add environment variables here if needed

[tasks]
# Optional: Define common tasks for your project
start = "npm run start"
build = "npm run build"
serve = "npm run serve"
